# Copyright 2021 CloudWeGo Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

services:
  mysql:
    image: "mysql:8"
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 1s
      timeout: 3s
      retries: 10
      start_period: 5s
  etcd:
    image: "quay.io/coreos/etcd:v3.6.7"
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"] # The health check command
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s
  jaeger:
    image: jaegertracing/all-in-one:latest
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "14268"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # 用户服务
  user:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE=user
    depends_on:
      mysql:
        condition: service_healthy
      etcd:
        condition: service_healthy
      jaeger:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "user", "8889"]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      - MYSQL_IP=mysql
      - ETCD_IP=etcd
      - JAEGER_AGENT_HOST=jaeger

  # 笔记服务
  note:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE=note
    depends_on:
      mysql:
        condition: service_healthy
      etcd:
        condition: service_healthy
      jaeger:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "note", "8888"]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      - MYSQL_IP=mysql
      - ETCD_IP=etcd
      - JAEGER_AGENT_HOST=jaeger

  # API服务
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE=api
    depends_on:
      user:
        condition: service_healthy
      note:
        condition: service_healthy
      etcd:
        condition: service_healthy
      jaeger:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "api", "8080"]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 15s
    environment:
      - MYSQL_IP=mysql
      - ETCD_IP=etcd
      - JAEGER_AGENT_HOST=jaeger
